//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Ex09a.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_EX09ATYPE                   129
#define IDD_DIALOG1                     130
#define IDB_BMBIRDSELECTED              130
#define IDB_BMDOG                       131
#define IDB_BMBIRD                      132
#define IDB_BMDOGSELECTED               133
#define IDB_BMFISH                      134
#define IDB_BMFISHSELECTED              135
#define IDI_RED                         137
#define IDI_BLACK                       138
#define IDI_BLUE                        139
#define IDI_GREEN                       140
#define IDI_PURPLE                      141
#define IDI_YELLOW                      142
#define IDI_CYAN                        143
#define IDI_WHITE                       144
#define IDC_DATETIMEPICKER1             1000
#define IDC_DATETIMEPICKER2             1001
#define IDC_DATETIMEPICKER3             1002
#define IDC_MONTHCALENDAR1              1003
#define IDC_DATETIMEPICKER4             1004
#define IDC_IPADDRESS1                  1005
#define IDC_COMBOBOXEX1                 1006
#define IDC_COMBOBOXEX2                 1007
#define IDC_STATIC1                     1008
#define IDC_STATIC2                     1009
#define IDC_STATIC3                     1010
#define IDC_STATIC4                     1011
#define IDC_STATIC5                     1012
#define IDC_STATIC6                     1013
#define IDC_STATIC7                     1014
#define IDC_STATIC8                     1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
